version: "3.8"

services:
    postgresql:
        image: postgres:12.16
        container_name: postgres
        restart: always
        ports:
           - "5432:5432"
        environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
      
    redis:
        image: redis:6.2.13
        container_name: redis
        restart: always
        ports:
          - "6379:6379"
